# Generated by Django 2.2 on 2023-10-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_auto_20231009_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='hobby_image',
            field=models.CharField(default='https://images.unsplash.com/photo-1532274402911-5a369e4c4bb5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%%3D%%3D&auto=format&fit=crop&w=2070&q=80', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='hobby_image',
            field=models.CharField(default='https://images.unsplash.com/photo-1532274402911-5a369e4c4bb5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%%3D%%3D&auto=format&fit=crop&w=2070&q=80', max_length=500),
        ),
    ]
