# Generated by Django 3.0.6 on 2023-10-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0007_auto_20231014_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='hobby_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSG3aLtQ7Ftn4hPxLlR8MuZt6xARYnsMQo2oA&usqp=CAU', max_length=2000),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_image',
            field=models.CharField(default='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSG3aLtQ7Ftn4hPxLlR8MuZt6xARYnsMQo2oA&usqp=CAU', max_length=2000),
        ),
    ]
